Repository rohanjsh/typeset, pull requests merged in 2023-12, with the labels that each got.

#34 feat: No need to wrap each word with literals 🥇
  README.md
  example/android/build.gradle
  example/lib/main.dart
  lib/src/core/type_controller.dart
  lib/src/models/type_enum.dart
  lib/src/models/type_value_model.dart
  lib/src/typeset.dart
  lib/src/typeset_parser.dart
Labels: enhancement

#35 Feat: Support for font size
  example/lib/main.dart
  lib/src/typeset_parser.dart
Labels: enhancement

#36 feat: v2.0 with upgraded core logic and features
  .github/workflows/main.yaml
  CHANGELOG.md
  README.md
  example/android/build.gradle
  example/lib/main.dart
  lib/src/core/typeset_controller.dart
  lib/src/core/typeset_parser.dart
  lib/src/core/typeset_reserved.dart
  lib/src/models/style_type_enum.dart
  lib/src/models/style_type_value_model.dart
  lib/src/scribble.dart
  lib/src/typeset.dart
  lib/src/typeset_parser.dart
  lib/typeset.dart
  pubspec.yaml
  test/src/typeset_test.dart
Labels: documentation, enhancement, bug-fix

#38 perf: google_fonts dependency
  CHANGELOG.md
  lib/src/core/typeset_parser.dart
  lib/src/scribble.dart
  lib/typeset.dart
  pubspec.yaml
Labels: dependencies

#39 refactor: make TypeSet.inputText a positional argument to match Text semantics
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/macos/Podfile.lock
  example/macos/Runner.xcodeproj/project.pbxproj
  example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/src/typeset.dart
  lib/src/typeset_ext.dart
  test/src/typeset_widget.dart
Labels: documentation, refactor
